---
- name: Install httpd
  hosts: localhost
  remote_user: ec2-user
  become: true
  
  tasks:
    - name: install yum httpd package
      yum:
        name: httpd
        state: present

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /home/ec2-user/Einstein.zip
        dest: /tmp
        remote_src: yes

    - name: Copy files
      copy:
        src: '/tmp/{{item}}'
        dest: /var/www/html/
        owner: ec2-user
      loop:
        - index.html
        - einstein.jpg  

    - name: Start and Enable httpd
      systemd:
        name: httpd
        state: started
        enabled: true



